spring.datasource.url=jdbc:postgresql://ep-plain-moon-anbf0prk.c-6.us-east-1.pg.koyeb.app:5432/koyebdb?sslmode=require
spring.datasource.username=koyeb-adm
spring.datasource.password=npg_pVKOyzM3wA8Z
